Code rewiew #2
enagtim/JavaScript-study pull request #2
Opened 2024-07-24 08:22 UTC by enagtim

2024-07-24 11:18 UTC, GitEsense requested changes
Задание №7 - `OK`
Задание №8 - `Переделать`
Задание №9 - `Оптимизировать`

2024-07-24 11:18 UTC, GitEsense commented on 7-converter/app.js
> +console.log(converter(1000, 'EURO','RUB'));
предложу вот такие вот варианты в качестве альтернативных вариантов решения:
**Вариант №1:**
```js
function converter(sum, currency, targetCurrency) {
    const USD = 90;
    const EUR = 100;

    currency = currency.toUpperCase();
    targetCurrency = targetCurrency.toUpperCase();

    switch (currency) {
        case 'USD':
            switch (targetCurrency) {
                case 'RUB':
                    return sum * USD;
                case 'EUR':
                    return (sum * USD) / EUR;
                default:
                    return null;
            }
        case 'EUR':
            switch (targetCurrency) {
                case 'RUB':
                    return sum * EUR;
                case 'USD':
                    return (sum * EUR) / USD;
                default:
                    return null;
            }
        case 'RUB':
            switch (targetCurrency) {
                case 'USD':
                    return sum / USD;
                case 'EUR':
                    return sum / EUR;
                default:
                    return null;
            }
        default:
            return null;
    }
}
```

**Вариант №2:**
```js
function convertSum(sum, from, to) {
    return ((sum * from) / to).toFixed(2);
}

function getTargetCurrencyIcon(targetCurrency) {
        switch (targetCurrency) {
            case 'RUB':
                return 'руб';
            case 'EUR':
                return '€';
            case 'USD':
                return '$';
            default: return '';
        }
}

function messageTemplate(value, icon){
    return `${value} ${icon}`;
}

function converter(sum, currency, targetCurrency) {
    const ALLOW_CURRENCY_LIST = ['RUB', 'EUR', 'USD'];
    const USD = 91.33;
    const RUB = 1;
    const EUR = 112.33;

    currency = currency.toUpperCase();
    targetCurrency = targetCurrency.toUpperCase();
    const icon = getTargetCurrencyIcon(targetCurrency);

    if (currency === targetCurrency) {
        return messageTemplate(sum, icon);
    }
    if (!ALLOW_CURRENCY_LIST.includes(currency)) {
        console.log('Входящая валюта мне неизвестна');
        return null;
    }
    if (!ALLOW_CURRENCY_LIST.includes(targetCurrency)) {
        console.log('Исходящая валюта мне неизвестна');
        return null;
    }
    
    let value = null;

    switch (currency) {
        case 'USD':
            switch (targetCurrency) {
                case 'RUB': value = convertSum(sum, USD, RUB); break;
                case 'EUR': value = convertSum(sum, USD, EUR); break;
            }; break;
        case 'RUB':
            switch (targetCurrency) {
                case 'USD': value = convertSum(sum, RUB, USD); break;
                case 'EUR': value = convertSum(sum, RUB, EUR); break;
            }; break;
        case 'EUR':
            switch (targetCurrency) {
                case 'RUB': value = convertSum(sum, EUR, RUB); break;
                case 'USD': value = convertSum(sum, EUR, USD); break;
            }; break;
    }

    return messageTemplate(value, icon)
}
```

**Вариант №3:**
```js
function convertSum(sum, from, to) {
    return ((sum * from) / to).toFixed(2);
}

function getTargetCurrencyIcon(targetCurrency) {
        switch (targetCurrency) {
            case 'RUB':
                return 'руб';
            case 'EUR':
                return '€';
            case 'USD':
                return '$';
            default: return '';
        }
}

function messageTemplate(value, icon){
    return `${value} ${icon}`;
}

function converter(sum, currency, targetCurrency) {
    const ALLOW_CURRENCY_LIST = [['RUB', 1], ['EUR', 112.33], ['USD', 91.33]];
    const flatList = ALLOW_CURRENCY_LIST.flat();
    currency = currency.toUpperCase();
    targetCurrency = targetCurrency.toUpperCase();

    if (!flatList.includes(currency)) {
        console.log('Входящая валюта мне неизвестна');
        return null;
    }
    if (!flatList.includes(targetCurrency)) {
        console.log('Исходящая валюта мне неизвестна');
        return null;
    }
    const icon = getTargetCurrencyIcon(targetCurrency);
    if (currency === targetCurrency) {
        return messageTemplate(sum, icon);
    }

    const currentIndex = flatList.indexOf(currency) / 2;
    const targetIndex = flatList.indexOf(targetCurrency) / 2;
    const [, currentValue] = ALLOW_CURRENCY_LIST[currentIndex];
    const [, targetValue] = ALLOW_CURRENCY_LIST[targetIndex];
    const result = convertSum(sum, currentValue, targetValue)
    return messageTemplate(result, icon);
}
```

2024-07-24 11:18 UTC, GitEsense commented on 8-crypto/app.js
> +}
Функция `check` не делает с паролем ничего, функция криптографии должна быть обратима, следовательно всё что делает функция check - это сравнивает пароль с "обратимостью" шифрованного пароля, т.е.

```js
function check(encryptPassword, password){
    // Тут хорошо бы сделать проверки для пароля и шифрованного, чтобы не сравнивать пустые строки
    return crypto(encryptPassword) ===  password
}
```

2024-07-24 11:18 UTC, GitEsense commented on 9-sort-loops/app.js
> +                arr[j + 1] = res;
А ведь я вчера Вам показывал трюк обмена переменными, почитайте 
https://learn.javascript.ru/destructuring-assignment

2024-07-24 11:18 UTC, GitEsense commented on 9-sort-loops/app.js
> +console.log(sort(arr));
Хорошо конечно, но функция модифицирует исходный массив, т.е. если мы сортируем, то массив array изменяется, давайте сделаем так, чтобы возвращался массив, не изменяя "исходный"

```js
const array = [1,3,2,5,4];

console.log(array) //[1,3,2,5,4]

const sortedArray = sort(array);

console.log(sortedArray) // [1,2,3,4,5]
console.log(array) //[1,3,2,5,4]
```

Так же я Вам вчера уже говорил про итерации (и полезность их сокращения) - на примере, так что хорошо бы их сократить

2024-07-26 09:06 UTC, enagtim commented on 9-sort-loops/app.js
> +console.log(sort(arr));
Коммиты по дз 8 и дз 9 добавил

2024-07-26 09:17 UTC, enagtim commented on 7-converter/app.js
> +console.log(converter(1000, 'EURO','RUB'));
Спасибо за альтернативные варианты!

2024-07-28 12:50 UTC, GitEsense requested changes
К сожалению пока ещё нет (

2024-07-28 12:50 UTC, GitEsense commented on 8-crypto/app.js
> +console.log(checkpassword('qwert','twerq'));
```js
const p = 'password' // Пароль
const e = crypto(p) // Шифрованный пароль
const d = crypto(e); // Расшифрованный пароль

console.log(p, e, d, p === d);
/* 
    Если p === d будет true, 
          то тогда задача будет верно решена (причём p можем быть разным)
*/
```

2024-07-28 12:50 UTC, GitEsense commented on 9-sort-loops/app.js
> +
но если тут вывести снова console.log(arr) - он будет сортирован... т.к. Вы работаете с ссылкой, а не "копией массива", посмотрите в стороны "spread оператора" или методов "извлечения значений" из массива

2024-07-28 15:26 UTC, enagtim commented on 9-sort-loops/app.js
> +
Спасибо за наводку! по учебнику JS, который вы скидывали ещё раз прочитал про методы работы с массивами и и обратился в slice, чтобы сделать копию массива и с ним работать. Теперь в консоле  выводится отсортированный массив и исходный!

2024-07-30 11:41 UTC, GitEsense approved these changes

2024-07-30 11:41 UTC, GitEsense commented on 9-sort-loops/app.js
> +    let newarray = array.slice();
Ещё можно было сделать просто 
```js
const newArray = [...array]
```

2024-07-30 11:41 UTC, GitEsense commented on 9-sort-loops/app.js
> +        for(let j = 0; j < arr.length - 1; j++ ) {
а тут уже работаем не с arr, а с newArray

2024-07-30 11:41 UTC, GitEsense commented on 9-sort-loops/app.js
> +
Вот, можете "ознакомиться" и проанализировать реализацию
```js
const numbers = Array.from({ length: 1000 }, () => {
    const max = 1000000;
    const min = 1000;
    const factor = Math.random() > 0.5 ? 1 : -1;
    const randomNumber = Math.ceil(Math.random() * (max - min)) + min;
    return randomNumber * factor;
});

function orderTemplate(firstNumber, secondNumber, desc) {
    if (!desc) {
        return firstNumber > secondNumber;
    }
    return firstNumber < secondNumber;
}

function sortArray(incomingArray, desc = false) {
    const array = [...incomingArray];
    for (let i = 0; i < array.length; i++) {
        for (let j = i; j < array.length; j++) {
            const isExchange = orderTemplate(array[i], array[j], desc);
            if (isExchange) {
                [array[i], array[j]] = [array[j], array[i]];
            }
        }
    }
    return array;
}

console.log(numbers);
console.log('Отсортированный по возрастанию массив:', sortArray(numbers));
console.log('Отсортированный по убыванию массив:', sortArray(numbers, true));

```

2024-07-30 11:41 UTC, GitEsense commented on 8-crypto/app.js
> +}
Функция принимает зашифрованный пароль и простой пароль, Вы же передаёте пароль, шифруете его и расшифровываете, по логике то же самое - но сравниваете шило на мыло (т.е. оно всегда будет верно, если функция обратима), но если передадим что-то другое - должно не сойтись и функция "check" должна иметь вид что-то вроде

```js 
function checkPassword (encryptPassword, password) {
   if(!encryptPassword || !password) {
        return false;
   }

   return crypto(encryptPassword) === password
}
```

2024-07-30 11:41 UTC, GitEsense commented on 8-crypto/app.js
> +}
```js
function crypt(password) {
    if (!password || !password.length) {
        return NaN;
    }
    const splitedArray = password.split('');
    if (splitedArray.length < 8) {
        return false;
    }

    const middleIndex = Math.floor(splitedArray.length / 2);
    const firstHalf = splitedArray.slice(0, middleIndex).reverse();
    const secondHalf = splitedArray.slice(middleIndex).reverse();
    const length = secondHalf.length;
    [secondHalf[1], secondHalf[length - 2]] = [secondHalf[length - 2], secondHalf[1]];

    const encryptedPassword = firstHalf.concat(secondHalf);
    return encryptedPassword.join('');
}

function checkPassword(encryptedPassword, originalPassword) {
    if (!encryptedPassword || !originalPassword) {
        return false;
    }
    return originalPassword === crypt(encryptedPassword);
}

function getRandomNumber(min = 0, max = 86) {
    return Math.ceil(Math.random() * (max - min)) + min;
}

function getRandomPassword(length = 12) {
    const symbolArray = Array.from({ length: 87 }, (_, index) => String.fromCharCode(index + 33));
    console.log(symbolArray);
    const password = Array.from({ length }, () => symbolArray[getRandomNumber()]);
    return password.join('');
}

/*
    logging and test function with console
*/

const password = getRandomPassword();
const encrypted = crypt(password);

console.log('Пароль:', password);
console.log('Зашифрованный пароль:', encrypted);
console.log('Проверка пароля:', checkPassword(encrypted, password));

const password2 = getRandomPassword();
const encrypted2 = crypt(password2).substring(1);

console.log('Пароль:', password2);
console.log('Зашифрованный пароль:', encrypted2);
console.log('Проверка пароля:', checkPassword(encrypted2, getRandomPassword()));
```

2024-07-31 06:04 UTC, merged